export { default as LoginPage } from './LoginPage.vue';
export { default as RegisterPage } from './RegisterPage.vue';
export { default as WelcomePage } from './WelcomePage.vue';
export { default as HomePage } from './HomePage.vue';
export { default as ShowAnimalsPage } from './ShowAnimalsPage.vue';
export { default as AnimalsPage } from './AnimalsPage.vue';
export { default as FarmerPage } from './FarmerPage.vue';
export { default as TestPage } from './TestPage.vue';
export { default as VetPage } from './VetPage.vue';
