export { default as LoginForm } from './LoginForm.vue';
export { default as FormInput } from './FormInput.vue';
export { default as VSelect } from './VSelect.vue';
export { default as VTextArea } from './VTextArea.vue';
export { default as VInput } from './VInput.vue';
export { default as AlertInput } from './AlertInput.vue';
export { default as VButton } from './VButton.vue';
export { default as VAlert } from './VAlert.vue';
export { default as VFormAnimal } from './VFormAnimal.vue';
